stages:
  preprocess:
    cmd: python preprocess_dataset.py
    deps:
    - preprocess_dataset.py
    - raw_dataset/weather.csv
    - utils_and_constants.py
    outs:
    - processed_dataset/weather.csv
  train:
    cmd: python train.py
    deps:
    - metrics_and_plots.py
    - model.py
    - processed_dataset/weather.csv
    - train.py
    - utils_and_constants.py
    # outs:
    # - confusion_matrix.png
    
    metrics:
      - metrics.json:
          cache: false
    plots:
      - predictions.csv:
          template: confusion
          x: predicted_label
          y: true_label
          x_label: 'Predicted label'
          y_label: 'True label'
          title: Confusion matrix
          cache: false




